# Звіт до роботи

## Тема: _Робота з числовими даними_

### Мета роботи: _Дослідити роботу з числовими даними_

---

### Виконання роботи



In [2]:
# Встановлення бібліотеки NumPy
%pip install numpy

# Функція для повідомлень
def homework(message):
    print("\n>>>>>", message, "\n")

# Імпортуємо бібліотеку NumPy
import numpy as np

# Початковий список температур
temperature = [20.1, 20.1, 20.2, 20.4]
print(f"Початковий список температур: {temperature}")

# Спроба множення списку на 5
t1 = temperature * 5
print(f"При множенні на 5 маємо: {t1}")
homework("Цей результат з'явився тому, що у Python операція `список * n` дублює вміст списку n разів, а не множить його елементи.")

# Використання спискового включення для правильного множення
t1 = [x * 5 for x in temperature]
print(f"Тепер отримаємо: {t1}")
homework("Цей результат з'явився тому, що ми використали спискове включення (list comprehension), яке множить кожен елемент списку на 5, створюючи новий список.")

# Створення масиву NumPy
t2 = np.array(temperature)
print(f"Масив з використанням методів NumPy: {t2}")

# Множення масиву NumPy на 5
t3 = t2 * 5
print(f"При множенні на 5 отримуємо: {t3}")
homework("NumPy дозволяє виконувати елементні операції напряму. Операція `t2 * 5` множить кожен елемент масиву на 5, що є частиною оптимізованої роботи з масивами у цій бібліотеці.")


Note: you may need to restart the kernel to use updated packages.
Початковий список температур: [20.1, 20.1, 20.2, 20.4]
При множенні на 5 маємо: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]

>>>>> Цей результат з'явився тому, що у Python операція `список * n` дублює вміст списку n разів, а не множить його елементи. 

Тепер отримаємо: [100.5, 100.5, 101.0, 102.0]

>>>>> Цей результат з'явився тому, що ми використали спискове включення (list comprehension), яке множить кожен елемент списку на 5, створюючи новий список. 

Масив з використанням методів NumPy: [20.1 20.1 20.2 20.4]
При множенні на 5 отримуємо: [100.5 100.5 101.  102. ]

>>>>> NumPy дозволяє виконувати елементні операції напряму. Операція `t2 * 5` множить кожен елемент масиву на 5, що є частиною оптимізованої роботи з масивами у цій бібліотеці. 



# Метод arange - генерує послідовність чисел з певним кроком у заданому інтервалі

In [3]:
import numpy as np

def homework(message):
    print("\n>>>>>", message, "\n")

# Початок і діапазон
start = 5
size_of_vec = 100

# Генерація масивів з range та arange
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {list(x)[0:5]} та методом arange: {a[0:5]}")
homework(f"Виведіть весь діапазон чисел. Масив з range: {list(x)}, масив з arange: {a.tolist()}")

# Масив із заданим початком
a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")
homework(f"Виведіть останній елемент у згенерованому масиві: {a[-1]}")

# Використання range із початком
x = range(start, size_of_vec)
print("Те саме але з вбудованою функцією range:", list(x))
homework(f"Виведіть якесь число з середини діапазону. Наприклад, середній елемент: {list(x)[len(x) // 2]}")

# Дробові числа
x = np.arange(10.4)
print("Будем мати:", x)
# Крок 0.5
x = np.arange(0.5, 4, 0.5)
print("З кроком 0.5:", x)
# Крок 0.08
x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x, "\nЗверніть увагу на заокруглення")
homework(f"Згенеруйте значення де крок буде мати чотири нулі після коми. Наприклад, крок 0.0001: {np.arange(0.0001, 0.001, 0.0001)}")

# Множення масиву
y = x * 2.5
print("Після перемноження:", y)
homework(f"Піднесіть отримане число до степеня 2 та поділіть на 0.4. Наприклад: {((y ** 2) / 0.4)}")


Масив згенерований простим range: [0, 1, 2, 3, 4] та методом arange: [0 1 2 3 4]

>>>>> Виведіть весь діапазон чисел. Масив з range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], масив з arange: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99] 

Можемо задавати початок генерації вектора, перший елемент: 5

>>>>

# Метод linspace - генерує задану кількістю чисел у певному діапазоні, 50 чисел за замовчуванням


In [4]:
import numpy as np

def homework(message):
    print("\n>>>>>", message, "\n")

# Початкові значення
start = 5
size_of_vec = 100

# Генерація чисел за допомогою np.linspace
a = np.linspace(start, size_of_vec)
print(f"Згенерували {len(a)} чисел в діапазоні {a[0]} до {a[-1]}")
homework("Виведіть кожне друге число згенерованого діапазону. Тут буде потрібен цикл :)")
print("Пояснення: Щоб вивести кожне друге число, використаємо цикл з кроком 2.")
# Виведення кожного другого числа
for i in range(0, len(a), 2):
    print(a[i])

# Зменшення кількості чисел до 5
print("\nМожна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(f"Результат: {a}")
homework("Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.")
print("Пояснення: Якщо ми задаємо 5 чисел, то вони рівномірно розподіляються між стартовим і кінцевим значенням.")

# Збільшення кількості чисел до 100
a = np.linspace(start, size_of_vec, 100)
print(f"Перші 10 чисел: {a[:10]}")
print(f"Останні 10 чисел: {a[-10:]}")
homework("Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.")
print("Пояснення: Кількість елементів в масиві збільшено до 100, отже між значеннями буде менший крок.")

# Виключення останнього значення з діапазону
print("""Як бачимо, перше та останнє значення завжди входять у згенерований діапазон.
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.
""")
print(np.linspace(start, size_of_vec, 5, endpoint=False))
homework("Спробуйте самі порахувати крок.")
print("Пояснення: Параметр 'endpoint=False' виключає останнє значення з діапазону, тому ми отримуємо рівномірний розподіл без останнього числа.")

# Отримання кроку з функцією retstep
_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(f"Для порівняння, ми можемо визначити крок автоматично, у нашому випадку це {sp_1} та {sp_2}")
homework("Чому маємо такий крок?")
print("Пояснення: Функція 'retstep=True' повертає значення кроку. Перший крок включає останнє значення, а другий — ні, що і впливає на результат.")


Згенерували 50 чисел в діапазоні 5.0 до 100.0

>>>>> Виведіть кожне друге число згенерованого діапазону. Тут буде потрібен цикл :) 

Пояснення: Щоб вивести кожне друге число, використаємо цикл з кроком 2.
5.0
8.877551020408163
12.755102040816325
16.632653061224488
20.51020408163265
24.387755102040817
28.26530612244898
32.14285714285714
36.0204081632653
39.89795918367347
43.775510204081634
47.6530612244898
51.53061224489796
55.40816326530612
59.285714285714285
63.16326530612245
67.0408163265306
70.91836734693878
74.79591836734694
78.6734693877551
82.55102040816327
86.42857142857143
90.3061224489796
94.18367346938776
98.06122448979592

Можна зменшити кількість чисел до 5:
Результат: [  5.    28.75  52.5   76.25 100.  ]

>>>>> Збільшіть кількість чисел до 100. Виведіть перших та останніх 10. 

Пояснення: Якщо ми задаємо 5 чисел, то вони рівномірно розподіляються між стартовим і кінцевим значенням.
Перші 10 чисел: [ 5.          5.95959596  6.91919192  7.87878788  8.83838384  9.7979798
 10.

# Типи масивів/векторів

In [5]:
import numpy as np

def homework(message):
    print("\n>>>>>", message, "\n")

# Тести з новими масивами
new_examples = {
    'Одновимірний вектор': np.array([1, 2, 3, 4, 5]), 
    'Двовимірна матриця': np.array([[1, 2], [3, 4], [5, 6]]), 
    'Трьохвимірна матриця': np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
}

for key in new_examples:
    print(f"Розглядаємо приклад з {key}. \nЗначення x буде: \n", new_examples[key])
    print(f"Тип {key} x: ", type(new_examples[key]))
    print(f"Розмірність/вимір {key} x:", np.ndim(new_examples[key]))
    print(f"Форма {key} x: ", new_examples[key].shape)
    print(f"Кількість елементів х: {np.size(new_examples[key])}")
    print("-=-"*10)

# Пояснення, чому значення для np.ndim та shape різні
homework("""Як Ви думаєте чому маємо такий результат для функції np.ndim (Розмірність/вимір/dimension).
Чому значення для векторів та матриць однакове та не співпдає з значенням shape?""")

# Пояснення, яке буде виведено:
print("""
Розмірність (np.ndim) визначає кількість осей або вимірів у масиві. Це може бути:
- 1: Одновимірний масив (вектор),
- 2: Двовимірний масив (матриця),
- 3: Тривимірний масив і так далі.

Форма (shape) визначає кількість елементів вздовж кожного виміру. Наприклад:
- Для одновимірного масиву shape = (3,) означає 3 елементи в одному вимірі.
- Для двовимірного масиву shape = (3, 1) означає 3 рядки, по 1 елементу в кожному.

Таким чином:
- Вектор-рядок (np.array([1, 2, 3])) має розмірність 1 (одновимірний масив), але форма цього масиву — (3,).
- Вектор-стовпець (np.array([[1], [2], [3]])) має розмірність 2 (двовимірний масив), і форма його — (3, 1).

Значення для np.ndim відрізняється від shape, оскільки форма описує кількість елементів по кожному виміру, а np.ndim дає загальну кількість вимірів. Тому навіть вектор-стовпець може мати розмірність 2, хоча він є "вектором" (одним стовпцем).
""")

Розглядаємо приклад з Одновимірний вектор. 
Значення x буде: 
 [1 2 3 4 5]
Тип Одновимірний вектор x:  <class 'numpy.ndarray'>
Розмірність/вимір Одновимірний вектор x: 1
Форма Одновимірний вектор x:  (5,)
Кількість елементів х: 5
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Двовимірна матриця. 
Значення x буде: 
 [[1 2]
 [3 4]
 [5 6]]
Тип Двовимірна матриця x:  <class 'numpy.ndarray'>
Розмірність/вимір Двовимірна матриця x: 2
Форма Двовимірна матриця x:  (3, 2)
Кількість елементів х: 6
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Трьохвимірна матриця. 
Значення x буде: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Тип Трьохвимірна матриця x:  <class 'numpy.ndarray'>
Розмірність/вимір Трьохвимірна матриця x: 3
Форма Трьохвимірна матриця x:  (2, 2, 2)
Кількість елементів х: 8
-=--=--=--=--=--=--=--=--=--=-

>>>>> Як Ви думаєте чому маємо такий результат для функції np.ndim (Розмірність/вимір/dimension).
Чому значення для векторів та матриць однакове та не співпдає з значенням sha

# Багатовимірні масиви, розуміння вимірів

In [6]:
import numpy as np

examples = {
    '5 рядків': np.array([[1], [2], [3], [4], [5]]), 
    '5 стовпців': np.array([[1, 2, 3, 4, 5]]),
    '5 елементів': np.array([[[1, 2, 3, 4, 5]]])
}

for a in examples:
    print(f"Для {a} маємо shape: \n{examples[a].shape} \nта вигляд: \n{examples[a]}")
    print(f"Розмірність (np.ndim) для {a}: {np.ndim(examples[a])}")
    print("-=-" * 10)

homework(f"Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів.")

# Пояснення, чому маємо такі результати:
print("""
1. Масив '5 рядків' має shape = (5, 1), що означає 5 рядків і 1 стовпець. Це є двовимірний масив (матриця) з 5 рядками.
2. Масив '5 стовпців' має shape = (1, 5), що означає 1 рядок і 5 стовпців. Це також двовимірний масив, але лише один рядок з 5 елементами.
3. Масив '5 елементів' має shape = (1, 1, 5), що є тривимірним масивом, де є один набір, один рядок та 5 елементів всередині.

Функція shape допомагає визначити кількість вимірів і розміри кожного виміру масиву:
- Для одновимірного масиву (вектора) shape = (N, ), де N — кількість елементів.
- Для двовимірного масиву (матриці) shape = (M, N), де M — кількість рядків, а N — кількість стовпців.
- Для тривимірного масиву shape = (P, M, N), де P — кількість "глибин" масиву, M — кількість рядків, а N — кількість стовпців.

Тепер давайте створимо ще декілька масивів з різною кількістю елементів:
""")

# Приклад додаткових масивів:
example1 = np.array([1, 2, 3, 4, 5])
example2 = np.array([[1, 2], [3, 4], [5, 6]])
example3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Виведемо їх форми та типи:
print(f"Масив example1 має shape = {example1.shape} та вигляд:\n{example1}")
print(f"Масив example2 має shape = {example2.shape} та вигляд:\n{example2}")
print(f"Масив example3 має shape = {example3.shape} та вигляд:\n{example3}")


Для 5 рядків маємо shape: 
(5, 1) 
та вигляд: 
[[1]
 [2]
 [3]
 [4]
 [5]]
Розмірність (np.ndim) для 5 рядків: 2
-=--=--=--=--=--=--=--=--=--=-
Для 5 стовпців маємо shape: 
(1, 5) 
та вигляд: 
[[1 2 3 4 5]]
Розмірність (np.ndim) для 5 стовпців: 2
-=--=--=--=--=--=--=--=--=--=-
Для 5 елементів маємо shape: 
(1, 1, 5) 
та вигляд: 
[[[1 2 3 4 5]]]
Розмірність (np.ndim) для 5 елементів: 3
-=--=--=--=--=--=--=--=--=--=-

>>>>> Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів. 


1. Масив '5 рядків' має shape = (5, 1), що означає 5 рядків і 1 стовпець. Це є двовимірний масив (матриця) з 5 рядками.
2. Масив '5 стовпців' має shape = (1, 5), що означає 1 рядок і 5 стовпців. Це також двовимірний масив, але лише один рядок з 5 елементами.
3. Масив '5 елементів' має shape = (1, 1, 5), що є тривимірним масивом, де є один набір, один рядок та 5 елементів всередині.

Функція shape допомагає визначити кількість вимірів і розміри кожного виміру мас

# Indexing and Slicing

In [7]:
import numpy as np

F = np.array([1, 1, 2, 3, 5, 8, 13, 21])

print(f"""Масив: {F}
Виміри: {F.shape}
Пам'ятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:\n {F[0]}
Другий:\n {F[1]}
Останній, {len(F)}: \n {F[7]}""")

print(f"""Можемо скористатись від'ємними індексами, якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:\n {F[-1]}
Передостанній:\n {F[-2]}""")

homework("Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами.")

# Пояснення:
print("""
1. В масиві F ми бачимо елементи Фібоначчі. Індексування масивів в Python починається з 0, тому:
- Перший елемент: F[0] дає значення 1.
- Другий елемент: F[1] дає значення 1.
- Останній елемент: F[7] дає значення 21.

2. В Python також можна використовувати від'ємні індекси, що дозволяє доступитись до елементів з кінця:
- Останній елемент: F[-1] дає значення 21 (це аналог F[7]).
- Передостанній елемент: F[-2] дає значення 13 (це аналог F[6]).

3. Ви можете практикуватись з доступом до елементів, спробуйте використати різні індекси для вибору елементів масиву F.
""")


Масив: [ 1  1  2  3  5  8 13 21]
Виміри: (8,)
Пам'ятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:
 1
Другий:
 1
Останній, 8: 
 21
Можемо скористатись від'ємними індексами, якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:
 21
Передостанній:
 13

>>>>> Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами. 


1. В масиві F ми бачимо елементи Фібоначчі. Індексування масивів в Python починається з 0, тому:
- Перший елемент: F[0] дає значення 1.
- Другий елемент: F[1] дає значення 1.
- Останній елемент: F[7] дає значення 21.

2. В Python також можна використовувати від'ємні індекси, що дозволяє доступитись до елементів з кінця:
- Останній елемент: F[-1] дає значення 21 (це аналог F[7]).
- Передостанній елемент: F[-2] дає значення 13 (це аналог F[6]).

3. Ви можете практикуватись з доступом до елементів, спробуйте використати різні індекси для вибору елементів масиву F.



In [8]:
import numpy as np

# Змінений масив
A = np.array([[2.3, 4.5, 6.7], 
              [7.1, -3.5, 1.2],
              [3.4, 9.8, 5.6],
              [8.9, -2.3, 0.4]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення, то візьметься цілий рядок:
    Перший рядок: {A[0]}
    Останній рядок: {A[-1]}
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: {A[:,0]}
    Останній стовпець: {A[:,-1]}
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: {A[0][0]} або {A[0, 0]}
    Останній елемент: {A[3][2]} або {A[-1][-1]} або {A[3, -1]}
""")

homework("Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементи, які належать діагоналі.")

# Пояснення:
print("""
1. У цьому масиві ми маємо 4 рядки і 3 стовпці. Для доступу до цілих рядків та стовпців ми використовуємо індексацію з одним значенням або з використанням двокрапки:
- A[0] — це перший рядок масиву.
- A[-1] — це останній рядок масиву.
- A[:, 0] — це перший стовпець, де двокрапка означає взяти всі елементи цього стовпця.
- A[:, -1] — це останній стовпець.
   
2. Для доступу до конкретних елементів використовуємо два індекси. Наприклад:
- A[0][0] або A[0, 0] — це перший елемент першого рядка.
- A[3][2] або A[-1][-1] або A[3, -1] — це останній елемент останнього рядка (0.4).

3. Якщо ви хочете доступитись до елементів, що належать діагоналі (елементи, де індекс рядка дорівнює індексу стовпця), ви можете використати індексацію:
- Діагональ масиву: A[0, 0], A[1, 1], A[2, 2], A[3, 3] і так далі.
""")


Масив:
[[ 2.3  4.5  6.7]
 [ 7.1 -3.5  1.2]
 [ 3.4  9.8  5.6]
 [ 8.9 -2.3  0.4]]
Виміри: (4, 3)
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення, то візьметься цілий рядок:
    Перший рядок: [2.3 4.5 6.7]
    Останній рядок: [ 8.9 -2.3  0.4]
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: [2.3 7.1 3.4 8.9]
    Останній стовпець: [6.7 1.2 5.6 0.4]
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: 2.3 або 2.3
    Останній елемент: 0.4 або 0.4 або 0.4


>>>>> Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементи, які належать діагоналі. 


1. У цьому масиві ми маємо 4 рядки і 3 стовпці. Для доступу до цілих рядків та стовпців ми використовуємо індексацію з одним значенням або з використанням двокрапки:
- A[0] — це перший рядок масиву.
- A[-1] — це останній рядок масиву.
- A[:, 0] — це перший стовпець, де двокрапка означає взяти всі елементи цього стовпця.
- A[:, -1] — це ост

In [9]:
import numpy as np

# Масив
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(f"""Масив:
{S}
Виміри: {S.shape}
Беремо декілька елементів: {S[2:5]}
Всі елементи до заданого: {S[:4]}
Всі елементи від заданого до кінця: {S[6:]}
Всі елементи: {S[:]}
""")

homework("Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву.")

# Пояснення:
print("""
1. У цьому масиві маємо 10 елементів. За допомогою індексації можемо вибирати частини масиву:
- S[2:5] — вибираємо елементи з індексами від 2 до 4 (не включно з 5).
- S[:4] — всі елементи до індексу 4 (не включаючи 4).
- S[6:] — всі елементи від індексу 6 до кінця.
- S[:] — вибираємо всі елементи масиву.

2. Використовуйте від'ємні індекси для доступу до елементів з кінця масиву. Наприклад:
- S[-4:] — вибираємо останні 4 елементи.
""")


Масив:
[0 1 2 3 4 5 6 7 8 9]
Виміри: (10,)
Беремо декілька елементів: [2 3 4]
Всі елементи до заданого: [0 1 2 3]
Всі елементи від заданого до кінця: [6 7 8 9]
Всі елементи: [0 1 2 3 4 5 6 7 8 9]


>>>>> Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву. 


1. У цьому масиві маємо 10 елементів. За допомогою індексації можемо вибирати частини масиву:
- S[2:5] — вибираємо елементи з індексами від 2 до 4 (не включно з 5).
- S[:4] — всі елементи до індексу 4 (не включаючи 4).
- S[6:] — всі елементи від індексу 6 до кінця.
- S[:] — вибираємо всі елементи масиву.

2. Використовуйте від'ємні індекси для доступу до елементів з кінця масиву. Наприклад:
- S[-4:] — вибираємо останні 4 елементи.



In [10]:
import numpy as np

# Новий масив
A = np.array([
    [17, 18, 19, 20, 21],
    [27, 28, 29, 30, 31],
    [37, 38, 39, 40, 41],
    [47, 48, 49, 50, 51],
    [57, 58, 59, 60, 61]
])

# Виведення результатів
print(f"""Масив:
{A}
Виміри: {A.shape}

Беремо декілька рядків:
{A[0:2]}

Два перші стовпці:
{A[:, 0:2]}

Два останні рядки:
{A[3:, :]}

Беремо підматрицю (нижні елементи):
{A[-3:, -3:]}
""")

# Пояснення:
print("""
1. Вибір кількох рядків: A[0:2] — вибирає перші два рядки з індексами 0 та 1. 
   Це дасть масив з перших двох рядків:
   [[17, 18, 19, 20, 21],
    [27, 28, 29, 30, 31]]
   
2. Вибір перших двох стовпців: A[:, 0:2] — вибирає перші два стовпці для всіх рядків.
   Це дасть:
   [[17, 18],
    [27, 28],
    [37, 38],
    [47, 48],
    [57, 58]]
   
3. Вибір останніх двох рядків: A[3:, :] — вибирає всі стовпці для останніх двох рядків.
   Це дасть:
   [[47, 48, 49, 50, 51],
    [57, 58, 59, 60, 61]]

4. Підматриця (нижні елементи): A[-3:, -3:] — вибирає останні три рядки і останні три стовпці масиву.
   Це дасть:
   [[39, 40, 41],
    [49, 50, 51],
    [59, 60, 61]]
""")



Масив:
[[17 18 19 20 21]
 [27 28 29 30 31]
 [37 38 39 40 41]
 [47 48 49 50 51]
 [57 58 59 60 61]]
Виміри: (5, 5)

Беремо декілька рядків:
[[17 18 19 20 21]
 [27 28 29 30 31]]

Два перші стовпці:
[[17 18]
 [27 28]
 [37 38]
 [47 48]
 [57 58]]

Два останні рядки:
[[47 48 49 50 51]
 [57 58 59 60 61]]

Беремо підматрицю (нижні елементи):
[[39 40 41]
 [49 50 51]
 [59 60 61]]


1. Вибір кількох рядків: A[0:2] — вибирає перші два рядки з індексами 0 та 1. 
   Це дасть масив з перших двох рядків:
   [[17, 18, 19, 20, 21],
    [27, 28, 29, 30, 31]]
   
2. Вибір перших двох стовпців: A[:, 0:2] — вибирає перші два стовпці для всіх рядків.
   Це дасть:
   [[17, 18],
    [27, 28],
    [37, 38],
    [47, 48],
    [57, 58]]
   
3. Вибір останніх двох рядків: A[3:, :] — вибирає всі стовпці для останніх двох рядків.
   Це дасть:
   [[47, 48, 49, 50, 51],
    [57, 58, 59, 60, 61]]

4. Підматриця (нижні елементи): A[-3:, -3:] — вибирає останні три рядки і останні три стовпці масиву.
   Це дасть:
   [[39, 

In [11]:
import numpy as np

# Створення масиву
A = np.arange(28).reshape(4, 7)

# Виведення результатів
print(f"""Масив:
{A}
Виміри: {A.shape}

Беремо кожен другий елемент першого рядка: 
{A[0, ::2]}

Беремо кожен третій елемент першого рядка: 
{A[0, ::3]}

Кожен другий елемент в кожному другому рядку: 
{A[::2, ::2]}

Останні три елементи в кожному другому рядку:
{A[::2, 4:]}

Можна повністю змінити порядок елементів (дзеркально обернемо):
{A[::-1, ::-1]}
""")

# Пояснення:
print("""
1. Вибір кожного другого елемента першого рядка:
   A[0, ::2] — вибираємо кожен другий елемент з першого рядка.
   Це дасть:
   [ 0, 2, 4, 6]

2. Вибір кожного третього елемента першого рядка:
   A[0, ::3] — вибираємо кожен третій елемент з першого рядка.
   Це дасть:
   [ 0, 3, 6]

3. Вибір кожного другого елемента в кожному другому рядку:
   A[::2, ::2] — вибираємо кожен другий елемент з кожного другого рядка.
   Це дасть:
   [[ 0, 2, 4, 6],
    [21, 23, 25, 27]]

4. Вибір останніх трьох елементів в кожному другому рядку:
   A[::2, 4:] — вибираємо останні три елементи з кожного другого рядка.
   Це дасть:
   [[ 4, 5, 6],
    [25, 26, 27]]

5. Обертання масиву дзеркально (перевертаємо рядки і стовпці):
   A[::-1, ::-1] — перевертаємо всі елементи масиву.
   Це дасть:
   [[27, 26, 25, 24, 23, 22, 21],
    [20, 19, 18, 17, 16, 15, 14],
    [13, 12, 11, 10,  9,  8,  7],
    [ 6,  5,  4,  3,  2,  1,  0]]
""")


Масив:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
Виміри: (4, 7)

Беремо кожен другий елемент першого рядка: 
[0 2 4 6]

Беремо кожен третій елемент першого рядка: 
[0 3 6]

Кожен другий елемент в кожному другому рядку: 
[[ 0  2  4  6]
 [14 16 18 20]]

Останні три елементи в кожному другому рядку:
[[ 4  5  6]
 [18 19 20]]

Можна повністю змінити порядок елементів (дзеркально обернемо):
[[27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14]
 [13 12 11 10  9  8  7]
 [ 6  5  4  3  2  1  0]]


1. Вибір кожного другого елемента першого рядка:
   A[0, ::2] — вибираємо кожен другий елемент з першого рядка.
   Це дасть:
   [ 0, 2, 4, 6]

2. Вибір кожного третього елемента першого рядка:
   A[0, ::3] — вибираємо кожен третій елемент з першого рядка.
   Це дасть:
   [ 0, 3, 6]

3. Вибір кожного другого елемента в кожному другому рядку:
   A[::2, ::2] — вибираємо кожен другий елемент з кожного другого рядка.
   Це дасть:
   [[ 0, 2, 4, 6],
    [21, 2

In [12]:
import numpy as np

# Масив від 0 до 49
A = np.arange(50)

# Створення умови для парних чисел
all_even = (A % 2 == 0)  # парні числа

# Створення комплексної умови для чисел, менших за 30 та поділених на 5 менших за 2
complex = (A < 30) & (A / 5 < 2) 

# Виведення результатів
print(f"""Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або {all_even[0]} для {A[0]} або {all_even[1]} для {A[1]}.
Після підставляння умови пошуку парних чисел в масив отримаємо:
{A[all_even]}
Або застосувавти більш комплексну умову з двох порівнянь:
{A[complex]}
""")

# Пояснення:
print("""
1. Умова для парних чисел (A % 2 == 0) дає масив True/False, в якому True вказує на парні числа в масиві.
   - all_even - масив, що містить True для кожного парного числа.

2. Комплексна умова (A < 30) & (A / 5 < 2) вказує, що вибираються числа менше 30, при цьому результат ділення на 5 повинен бути меншим за 2.
   - complex - масив, що містить True для чисел, які задовольняють обидві умови.

3. Для того, щоб отримати конкретні елементи з масиву, ми використовуємо умовну індексацію:
   - A[all_even] повертає всі парні числа з масиву.
   - A[complex] повертає всі числа, які відповідають комплексній умові.

""")



Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або True для 0 або False для 1.
Після підставляння умови пошуку парних чисел в масив отримаємо:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
Або застосувавти більш комплексну умову з двох порівнянь:
[0 1 2 3 4 5 6 7 8 9]


1. Умова для парних чисел (A % 2 == 0) дає масив True/False, в якому True вказує на парні числа в масиві.
   - all_even - масив, що містить True для кожного парного числа.

2. Комплексна умова (A < 30) & (A / 5 < 2) вказує, що вибираються числа менше 30, при цьому результат ділення на 5 повинен бути меншим за 2.
   - complex - масив, що містить True для чисел, які задовольняють обидві умови.

3. Для того, щоб отримати конкретні елементи з масиву, ми використовуємо умовну індексацію:
   - A[all_even] повертає всі парні числа з масиву.
   - A[complex] повертає всі числа, які відповідають комплексній умові.




# Функції для створення матриць: ones, zeros, identity, eye, empty

In [13]:
import numpy as np

# Створення масивів
o = np.ones(5)  # масив з одиниць
z = np.zeros(5)  # масив з нулів
i = np.identity(5)  # одинична матриця 5x5
e = np.eye(5)  # одинична матриця з діагоналлю 1
t = np.empty(5)  # порожня матриця з випадковими значеннями

# Виведення результатів
print(f"""
Всі елементи 1:
{o}
Всі елементи 0:
{z}
Матриця в якої діагональ всі 1:
{i}
Також, діагональ всі 1 (зменшимо вивід):
{e[:2, :2]}
Пуста матриця буде містити набір випадкових чисел які записані у пам'ять де був ініціалізований масив:
{t}
""")



Всі елементи 1:
[1. 1. 1. 1. 1.]
Всі елементи 0:
[0. 0. 0. 0. 0.]
Матриця в якої діагональ всі 1:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Також, діагональ всі 1 (зменшимо вивід):
[[1. 0.]
 [0. 1.]]
Пуста матриця буде містити набір випадкових чисел які записані у пам'ять де був ініціалізований масив:
[5.40446738e-310 0.00000000e+000 5.40446729e-310 5.40446733e-310
 2.37151510e-322]



In [14]:
import numpy as np

# Створення масивів
o = np.ones(5)  # масив з одиниць
z = np.zeros(5)  # масив з нулів
i = np.identity(5)  # одинична матриця 5x5
e = np.eye(5)  # одинична матриця з діагоналлю 1
t = np.empty(5)  # порожня матриця з випадковими значеннями

# Виведення результатів
print(f"""
Всі елементи 1:
{o}
Всі елементи 0:
{z}
Матриця в якої діагональ всі 1:
{i}
Також, діагональ всі 1 (зменшимо вивід):
{e[:2, :2]}
Пуста матриця буде містити набір випадкових чисел які записані у пам'ять де був ініціалізований масив:
{t}
""")



Всі елементи 1:
[1. 1. 1. 1. 1.]
Всі елементи 0:
[0. 0. 0. 0. 0.]
Матриця в якої діагональ всі 1:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Також, діагональ всі 1 (зменшимо вивід):
[[1. 0.]
 [0. 1.]]
Пуста матриця буде містити набір випадкових чисел які записані у пам'ять де був ініціалізований масив:
[0. 0. 0. 0. 0.]



# # Восьме завдання

In [15]:
import numpy as np

# Створення векторів
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Створення матриць
matrix1 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])

# Виведення розмірностей
print(f"Розмірність vector1: {vector1.shape}")
print(f"Розмірність vector2: {vector2.shape}")
print(f"Розмірність matrix1: {matrix1.shape}")
print(f"Розмірність matrix2: {matrix2.shape}")

# Арифметичні операції

# Додавання векторів
vector_sum = vector1 + vector2
print(f"Сума векторів: {vector_sum}")

# Віднімання векторів
vector_diff = vector1 - vector2
print(f"Різниця векторів: {vector_diff}")

# Множення вектора на число
vector_scalar_mult = vector1 * 2
print(f"Множення вектора на скаляр: {vector_scalar_mult}")

# Додавання матриць
matrix_sum = matrix1 + matrix2
print(f"Сума матриць: \n{matrix_sum}")

# Множення матриць
matrix_mult = np.dot(matrix1, matrix2.T)  # Перемноження матриць
print(f"Множення матриць: \n{matrix_mult}")

# Складання вектора і матриці (не обов'язково однакових розмірностей)
try:
    vector_matrix_sum = matrix1 + vector1  # Не можна додавати матрицю і вектор без відповідних розмірностей
    print(f"Сума матриці і вектора: \n{vector_matrix_sum}")
except ValueError as e:
    print(f"Помилка при додаванні вектора і матриці: {e}")


Розмірність vector1: (3,)
Розмірність vector2: (3,)
Розмірність matrix1: (3, 2)
Розмірність matrix2: (3, 2)
Сума векторів: [5 7 9]
Різниця векторів: [-3 -3 -3]
Множення вектора на скаляр: [2 4 6]
Сума матриць: 
[[ 8 10]
 [12 14]
 [16 18]]
Множення матриць: 
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]]
Помилка при додаванні вектора і матриці: operands could not be broadcast together with shapes (3,2) (3,) 


---
### Висновок:

- :question: Що зроблено в роботі;
* завдання
- :question: Чи досягнуто мети роботи;
* так
- :question: Які нові знання отримано;
* пов'язані з python
- :question: Чи вдалось відповісти на всі питання задані в ході роботи;
* yes
- :question: Чи вдалося виконати всі завдання;
* yes
- :question: Чи виникли складності у виконанні завдання;
* no
- :question: Чи подобається такий формат здачі роботи (Feedback);
* yes
- :question: Побажання для покращення (Suggestions);
* don't have

---